# Generated by Django 5.0.4 on 2024-04-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contato", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="picture",
            field=models.ImageField(blank=True, upload_to="pictures/%Y/%m"),
        ),
        migrations.AddField(
            model_name="contato",
            name="show",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="contato",
            name="descripion",
            field=models.TextField(blank=True),
        ),
    ]
